version: "3"

services:

  web:
    build: .
    container_name: web
    ports:
      - 5000:5000
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "True"
  
  postgres:
    image: postgres:13.3
    environment:
#      POSTGRES_DB: "market"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      #PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: fumeron@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 777778
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
        - 8080:80

volumes:
  db-data:
  pgadmin-data:



